app_accueil:
    resource: AppBundle\Controller\AssociationController
    type: rest 

app_commune:
    resource: app.commune
    type: sylius.api
    prefix: /api

app_poste:
    resource: app.poste
    type: sylius.api
    prefix: /api

app_quartier:
    resource: app.quartier
    type: sylius.api
    prefix: /api

app_membre:
    resource: app.membre
    type: sylius.api
    prefix: /api

app_organigramme:
    path: /api/postes/node/{node}
    methods: [GET]
    defaults:
        _controller: app.controller.poste:indexAction
        _sylius:
            criteria:
                ordreHierarchie: $node