<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends EntityRepository
{
    public function findByPoste(){
        $qb = $this->createQueryBuilder('m');
/*            ->leftJoin('m.poste','poste')
            ->orderBy('m.poste.ordreHierarchie','DESC');*/
        return $qb->getQuery()->getResult();
    }
}
